### ISSUE TITLE
Calling path.prune() inserts a semicolon

### ISSUE THREAD

**Issue by splodingsocks** [benjamn/ast-types#129]
Hi there! This is probably something I'm doing wrong, but this is the best place I could think to ask for help.

I'm using https://github.com/facebook/jscodeshift (which uses this repo) to remove some comments from a codebase. Here's an example snippet of the source: 

```javascript
function foo() {
  // A comment <-- Remove me!
  var a = 5
  return a
}
```

I run this little script on it:

```javascript
module.exports = function(fileInfo, api) {
  let j = api.jscodeshift

  function removeComments(src) {
    return src.find(j.Comment)
    .forEach(path => {
      path.prune()
    })
  }

  let src = api.jscodeshift(fileInfo.source)
  removeComments(src)

  return src.toSource()
}
```

(That's using the wrapper syntax from codeshift, sorry, I'm not familiar with this Library's API directly)

And here's the output I get afterward:

```javascript
function foo() {
  var a = 5;
  return a
}
```

The comment is gone, which is great, but a semicolon has been inserted on the line which used to follow the comment.

This normally might not be a big deal, but the style standards of the codebase require the semicolons not be used most of the time.

Can you help me figure out what's going wrong?

Thanks so much for this fantastic module. It's very impressive :)

**Comment by kyldvs** [comment]
This probably happens because the comment is attached to the variable declaration node, check out: http://astexplorer.net/#/uiWOg7cG3j

So the node has changed and it has to be reprinted and the default is probably to print with a semi-colon. I wonder if recast could be non-destructive if only comments change?

**Comment by splodingsocks** [comment]
Hmm, the example you sent me uses the Acorn parser, and I don't see comments represented at all in that structure. How do you know it's attached to the variable declarator?

When I switch it to the Babylon parser I see the comments, but they're detached in their own branch at the root of the JSON tree.

**Comment by splodingsocks** [comment]
And thanks for your help!

**Comment by splodingsocks** [comment]
Ah, I see, so this is really an issue for recast, making semicolons configurable.

Here's the line where the semicolon was being added, for future reference: https://github.com/benjamn/recast/blob/e9e847d7116c55299e3a0c5427e57787762803fb/lib/printer.js#L791

Thanks again.

**Comment by splodingsocks** [comment]
I mean, this is the line :)

https://github.com/benjamn/recast/blob/e9e847d7116c55299e3a0c5427e57787762803fb/lib/printer.js#L1277

**Comment by kyldvs** [comment]
Ooops, sorry if I sent a bad link. I promise it was on babylon when I saved :P

**Comment by kyldvs** [comment]
I believe it will be challenging to get that option added to recast. As soon as you stop using semicolons AST nodes need context way more often. For example consider this quick example

```javascript
var x = 4
+4;
console.log(x) // 8

var y = 4;
+4;
console.log(y) // 4
```

So now in order to print a variable declaration without a semi-colon you must have context of the next node in order to ensure it's not some expression statement that could be parsed in a way to influence the declaration.

**Comment by kyldvs** [comment]
And this is how the comment attaches to the variable declaration node in babylon in case you couldn't get astexplorer to behave.

<img width="1455" alt="screen shot 2015-10-02 at 2 27 37 am" src="https://cloud.githubusercontent.com/assets/1830497/10243412/42aec218-68ad-11e5-90c3-e5540a69aa7a.png">

**Comment by splodingsocks** [comment]
Ah, there it is! Thanks for finding that for me.

I see your point about context and semicolons.

It seems reasonable to me that Recast could accept a flag, or an option to specify that the codebase doesn't use semicolons. If this were the case, it's likely that the kind of bugs you pointed out above would already be considered and avoided, since the original author took those possibilities into account when writing the code. But that's a discussion that would be better had on a thread in the Recast repo, I imagine.

**Comment by benjamn** [comment]
You might be able to remove semicolons in a post-processing step with this tool: https://github.com/yyx990803/semi

**Comment by splodingsocks** [comment]
That'd be a great solution. Thanks @benjamn!
