### ISSUE TITLE
flow’s type declaration

### ISSUE THREAD

**Issue by iamdustan** [benjamn/ast-types#131]
it appears as though the type declaration for flow isn’t supported; or at least causes unexpected output.

```
type User = {
  firstName: string;
  lastName: string;
  age?: number;
};

const fullName = (props:User) => `${props.firstName} ${props.lastName}`;
```

**Comment by iamdustan** [comment]
not sure if this is actually valid or not, but I realized the error message I was getting was a bit off and tracked my issue down. mah bad.

**Comment by benjamn** [comment]
no worries :)
