### ISSUE TITLE
Split fb-harmony into flow and jsx

### ISSUE THREAD

**Issue by danez** [benjamn/ast-types#138]
Not sure what you think about this, but I think flow and jsx definitions, which are currently in one file should be splitted in separate files, separated by technology.

At least I think the name is somehow weird, as all the definitions don't have anything todo with es6 (harmony) anymore, but are just additions in form of jsx or flow.

Does this make seens? What do you think about that? 

This would probably also help if #57 gets merged.

**Comment by benjamn** [comment]
Yeah this totally makes sense!
