### ISSUE TITLE
Fails with import { ... } from '...';

### ISSUE THREAD

**Issue by alitaheri** [benjamn/ast-types#139]
We use recast in our library and using `import { ... } from '...';` syntax for files that we want to parse leads to the following error. I'm guessing that form is not yet supported.

To see the failure live check out [this PR](https://github.com/callemall/material-ui/pull/2825).

```
Uncaught Error: [{type: ImportSpecifier, start: 170, end: 177, loc: [object Object], imported: [object Object], local: [object Object], id: null, name: null}] does not match type 
PrintableTp.assert @ types.js:56
genericPrintNoParens @ printer.js:219
genericPrint @ printer.js:164
printRootGenerically @ printer.js:105
maybeReprint @ printer.js:97
print @ printer.js:75
exports.printComments @ comments.js:324
printWithComments @ printer.js:61
print @ printer.js:66
Printer.print @ printer.js:118
print @ main.js:6
printValue @ printValue.js:34
getDefaultValue @ defaultPropsHandler.js:54
...
```

**Comment by fkling** [comment]
Recast supports this just fine: http://astexplorer.net/#/ZYABOiSJC1 . Can you provide more context? Which version, parser, settings are you using?

**Comment by alitaheri** [comment]
Thanks for the quick answer. If that is the case I'll investigate further to see what is causing it. It might be webpack again. Some times it messes up different versions that are included inside the dependency tree. The bundle might be actually using something different for some of it's indirect dependencies. I'll get back to this. Thank you.

**Comment by fkling** [comment]
That would have been my first guess actually, that somehow multiple different versions / instances are being used.

**Comment by alitaheri** [comment]
I did a lot of investigation. The issue persists no matter what version I use. maybe it's not related to that syntax. I have to dig a lot deeper.

**Comment by alitaheri** [comment]
I will work around this issue for now. besides if that demo works then it must be webpack. So I'm closing. Thanks for your time :+1:
