### ISSUE TITLE
0.8.18 tag is missing from the repo; no corresponding tag for NPM 0.8.18 version

### ISSUE THREAD

**Issue by jessebeach** [benjamn/ast-types#172]
Hi hi, I can't find a corresponding commit for the NPM 0.8.18 version. Perhaps the 0.8.18 version wasn't published to this repo?

**Comment by jessebeach** [comment]
https://www.npmjs.com/package/ast-types

'0.8.18': '2016-06-29T15:08:05.096Z'

**Comment by jessebeach** [comment]
Looks like this is the commit for 0.8.18

commit 06ed2a9e1f89f8a0cc51a110fff6cbbe48197e65
Author: Ben Newman <ben@benjamn.com>
Date:   Wed Jun 29 11:05:00 2016 -0400

    Bump NPM version to 0.8.18 in preparation for publishing.

**Comment by benjamn** [comment]
Yes, that's it. I also just pushed the `v0.8.18` tag (along with `v0.9.0`), in case that helps.

**Comment by jessebeach** [comment]
Neat, thanks Ben!
