### ISSUE TITLE
ForAwaitStatement

### ISSUE THREAD

**Issue by samwgoldman** [benjamn/ast-types#186]
The [async iteration proposal](https://github.com/tc39/proposal-async-iteration) is stage 3 and ready for implementation. Babylon adds support and uses a `ForAwaitStatement`, which is identical to the `ForOf` statement except for the name.

**Comment by benjamn** [comment]
Any chance you have time to open a pull request? I believe you'd want to modify [this file](https://github.com/benjamn/ast-types/blob/master/def/babel.js).

**Comment by samwgoldman** [comment]
Will do :)

**Comment by hzoo** [comment]
can close this too
