### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Pajn** [benjamn/ast-types#213]
Hello!
There is an ongoing effort to add TypeScript support to prettier. To do this, [typescript-eslint-parser](https://github.com/eslint/typescript-eslint-parser) is used to convert the AST from TypeScript into an estree compatible format. Due to some additional syntax, additional node types is required. It would be awesome to collect those here.

I have started defining some of them [here](https://github.com/Pajn/ast-types/commit/2e2a468e4283e69e1d11c71c25e2e61c4b4ee1cf). So I opened this issue to check with you first, if you are interested in integrating this at all and secondly, how to handle the development process.
To not create to big PRs and ease collaboration it would be great to integrate often which mean that these types will be extended and may see some churn until things stabilize. Should I hold off sending these to you now and instead include them in the prettier PR so that they can move from there at a later point in time or do you prefer to keep the development here?

**Comment by benjamn** [comment]
Please feel free to open a WIP pull request with these changes, and push to it as you add more types. Thanks for working on this!

**Comment by benjamn** [comment]
I would love to support the full un-converted TypeScript AST at some point, but that's obviously a lot more work.

**Comment by georgeedwards** [comment]
Disclaimer: I am fairly far out of my knowledge zone here - but I am trying to add Typescript support to the [`feathers-cli`](https://github.com/feathersjs/feathers-cli) whihc is dependant on [this](https://github.com/facebook/jscodeshift/issues/180) and in turn dependant on [recast](https://github.com/benjamn/recast/issues/424#issuecomment-324028011). 

However, two thoughts, 

1. Can we not use the TypeScript's compiler [API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-simple-transform-function) which has AST support, or at least see the sourcecode for the API?

2. How about using he [tscodeshift](https://github.com/KnisterPeter/tscodeshift) project as a startign point for AST definitons for TypeScript?

Appologies if I have missunderstood what is required here.
