### ISSUE TITLE
Versioning gone wrong

### ISSUE THREAD

**Issue by SnarkBoojum** [benjamn/ast-types#233]
Hi,

package.json and the commit messages say you released 0.9.13... but you tagged 0.24.7, and hence Debian detects that version as the last official one.

May I ask you to re-tag?

Thanks!

**Comment by SnarkBoojum** [comment]
Notice that as long as github lists a version 0.24.7, my scripts will detect it as the most current version.

**Comment by benjamn** [comment]
Fixed, but I really don't understand why Debian would use GitHub as the source of truth here, rather than npm.

**Comment by SnarkBoojum** [comment]
Because Debian is a distribution, using the sources of the software it packages. Npm is another distribution, so not a source.
