### ISSUE TITLE
Inaccurate node engines requirement

### ISSUE THREAD

**Issue by chrisakers** [benjamn/ast-types#255]
This library's `engines` specification [in package.json](https://github.com/benjamn/ast-types/blob/efe89144c033d7b83c4351f676dbc8f66a2c5303/package.json#L45) has:
```json
"engines": {
    "node": ">= 0.8"
  }
```
But this library also uses fat arrow functions (E.g. [flow.js](https://github.com/benjamn/ast-types/blob/9a704d7cfc63bb264e7d6290e84627e0fad41d28/def/flow.js#L247)) which isn't compatible in node<4.

**Comment by benjamn** [comment]
Yes indeed! Would you mind submitting a PR to update the minimum version to Node 4?
