### ISSUE TITLE
Tag v0.11.5 missing

### ISSUE THREAD

**Issue by baremetalfreak** [benjamn/ast-types#285]
On npm, there is a version [0.11.5](https://www.npmjs.com/package/ast-types/v/0.11.5) but this repo does not have such a tag. Could you, please, add it so it is clear what particular commit it refers to? Thank you.

**Comment by benjamn** [comment]
Forgot to run `git push --tags`, sorry!

**Comment by baremetalfreak** [comment]
Thanks!
