### ISSUE TITLE
path.scope.isGlobal should be true for identifiers in arrow functions

### ISSUE THREAD

**Issue by GianlucaGuarini** [benjamn/ast-types#293]
The  `path.scope.isGlobal` property should be `true` for identifiers located in arrow functions since the scope doesn't change:

```js
const recast = require('recast')
const types = recast.types
const assert = require('assert')

const code = '(bar) => foo'
const ast = recast.parse(code)

types.visit(ast, {
    visitIdentifier(path) {
      assert(path.scope.isGlobal, true)
      this.traverse(path)
    }
})

console.log(ast)
```

[demo](https://runkit.com/gianlucaguarini/5bd2b400e08b000012bdbbd8)

Notice also that in case of functions with arguments the `isGlobal` property should be only true if the identifier wasn't previously defined as function argument

```js
// the foo argument should return isGlobal=true
// the bar identifier should return isGlobal=true
// the foo in the function body was defined as argument so it should return isGlobal=false
(foo) => bar + foo
```

**Comment by jedwards1211** [comment]
@GianlucaGuarini I don't think this is correct.  An arrow function *does* introduce a new lexical scope; it just doesn't shadow the value bound to `this` on the enclosing scope, which I think has confused many people into thinking it doesn't introduce a new lexical scope.

The following code demonstrates that an arrow function introduces a new lexical scope, unlike a loop:
```js
var foo = 'outer';
(() => {
  var foo = 'inner'; // doesn't overwrite foo on global scope
})();
console.log(foo); // 'outer'

var bar = 'outer';
do {
  var bar = 'inner'; // overwrites bar on global scope
} while (false);
console.log(bar); // 'inner'
```

**Comment by jedwards1211** [comment]
Yes, `Scope.lookup(name)` returns the scope that actually defines `name`, so the following should work:
```js
function isGlobal(path, name) {
  const scope = path.scope.lookup(name)
  if (!scope) throw new Error(`identifier not found: ${name}`)
  return scope.isGlobal
}
```
This won't work for built-in globals though, since the AST only has information about explicitly defined global identifiers.  So you may want to check against a list of built-in global identifiers as well.

**Comment by GianlucaGuarini** [comment]
Ok that should be enough. Thank you so much for your help and for your time
