### ISSUE TITLE
Support `ChainExpression` type for optional chaining

### ISSUE THREAD

**Issue by mjhenkes** [benjamn/ast-types#383]
# Feature request or bug?

babelParser@7.11.0 changed how optional chaining gets represented in an AST. Previously the optional chain was represented as an `OptionalMemberExpression`, now the optional chain is broken into two nodes a `ChainExpression` and a `MemberExpression`.

I asked babel if this was a breaking change and they clarified that this is an intentional change. See [Babel issue #11908](https://github.com/babel/babel/issues/11908)

I stumbled upon this while trying to use react-doc-gen against a component with optional chanining and the ast-types library that it uses fails when it tries to understand the 'ChainExpression' type. See [react-doc-gen issue #463](https://github.com/reactjs/react-docgen/issues/463)

I'm currently working around this issue by locking in the projects babel dependencies in the package.json

For example:

```diff
  "devDependencies": {
-    "@babel/core": "^7.5.0",
+    "@babel/core": "7.10.5",
+    "@babel/parser": "7.10.5",
```

However this isn't a good long term fix. I would be ideal if ast-types was updated to support the `chainExpression` type.

**Comment by ethancrook99** [comment]
I made a PR for a possible fix [here](https://github.com/benjamn/ast-types/pull/399).

**Comment by mjhenkes** [comment]
Thank you @ethancrook99 and @benjamn ❤️
