### ISSUE TITLE
Question: Should `tslib` be a dependency or a dev dependency? 

### ISSUE THREAD

**Issue by mjhenkes** [benjamn/ast-types#415]
I noticed `tslib` was added as a dependency. I'm not super familiar with typescript but it seemed to stick out as the only non dev dependency and it seems like it's only used in internal typescript.
https://github.com/benjamn/ast-types/blob/master/package.json#L40

Added here:
https://github.com/benjamn/ast-types/commit/03d6467df0d9edb1abf13da741e3f81e847feee6

**Comment by benjamn** [comment]
Definitely a non-dev dependency, as it provides a runtime library for TypeScript-generated code!
