### ISSUE TITLE
[Flow] Exception on indexed access types

### ISSUE THREAD

**Issue by pascalduez** [benjamn/ast-types#596]
Using recent Flow "indexed access types" we get the following exception:
```
did not recognize object of type "IndexedAccessType"
```
See https://flow.org/en/docs/types/indexed-access

`ast-types@0.14.2`

**Comment by sziberov** [comment]
Same goes for "PropertyDefinition".

**Comment by pascalduez** [comment]
Support for `IndexedAccessType` added in https://github.com/benjamn/ast-types/pull/514

**Comment by buschco** [comment]
For `PropertyDefinition` I opened another issue -> https://github.com/benjamn/ast-types/issues/728
