### ISSUE TITLE
Function can have an expression as a body?

### ISSUE THREAD

**Issue by jamestalmage** [benjamn/ast-types#96]
```javascript
// core.js
def("Function")
    .bases("Node")
    .field("id", or(def("Identifier"), null), defaults["null"])
    .field("params", [def("Pattern")])
    .field("body", or(def("BlockStatement"), def("Expression")));
```

What would an ES5 function without a block statement look like? Is this just here to support arrow functions in ES6? If so, wouldn't it be better to override it in `es6.js`?

**Comment by benjamn** [comment]
Yep, that's left over from the original [Mozilla Parser API](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API#Functions) (see the note). It's actually still possible (in SpiderMonkey) to write `function increment(x) x + 1`.

**Comment by jamestalmage** [comment]
interesting.

This works:
```javascript
var ast = b.functionDeclaration(
  b.identifier('me'),
  [],
  b.binaryExpression(
    '+',
    b.identifier('foo'),
    b.literal(1)
  )
);
```

But if you try to print it it throws.

**Comment by jamestalmage** [comment]
Esprima seems to [throw an error](http://esprima.org/demo/parse.html?code=function%20inc(x)%20x%20%2B%201%0A) when parsing `function increment(x) x + 1` anyways.
