### ISSUE TITLE
add expressionStatement wrappers for builders

### ISSUE THREAD

**Issue by jamestalmage** [benjamn/ast-types#97]
`b.assigmentStatement(...)` ==> `b.expressionStatement(b.assignmentExpression(...))`

`b.callStatement(...)` ==> `b.expressionStatement(b.callExpression(...))`

Similar for `updateExpression`, `logicalExpression`, and possibly for everything that `bases('Expression')`.

Somebody had a similar idea:
```javascript
// core.js
// ...
// TODO Figure out how to silently coerce Expressions to
// ExpressionStatements where a Statement was expected.
```

But I think this provides similar convenience without silently swallowing developer mistakes.

**Comment by benjamn** [comment]
Ahh, I like this idea!

**Comment by jamestalmage** [comment]
Want a PR?

**Comment by benjamn** [comment]
Sure :)
